name: Version Update

on:
  repository_dispatch:
    types: [version_update]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update version
        run: |
          npm install semver
          VERSION_UPDATE_TYPE="${{ github.event.client_payload.type }}"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(node -p "require('semver').inc('$CURRENT_VERSION', '$VERSION_UPDATE_TYPE')")
          jq ".version=\"$NEW_VERSION\"" package.json > package.tmp.json && mv package.tmp.json package.json
          jq ".version=\"$NEW_VERSION\"" public/manifest.json > manifest.tmp.json && mv manifest.tmp.json public/manifest.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json public/manifest.json
          git commit -m "Update version to $NEW_VERSION"
          git push
